GraniteHouse/Areas/Admin/Controllers/AdminUsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GraniteHouse.Data;
using GraniteHouse.Models;
using GraniteHouse.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace GraniteHouse.Areas.Admin.Controllers
{
    [Authorize(Roles = SD.SuperAdminEndUser)]
    [Area("Admin")]
    public class AdminUsersController : Controller
    {

        private readonly ApplicationDbContext _db;
       

        public AdminUsersController(ApplicationDbContext db)
        {
            _db = db;
        }


      
        public IActionResult Index()
        {
            return View(_db.ApplicationUser.ToList() );
        }


        // get Edit
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null || id.Trim().Length==0)
            {
                return NotFound();  // NotFound() base controller method that returns a 404 html error.
            }

            var userFromDb = await _db.ApplicationUser.FindAsync(id);
           
            if (userFromDb == null)
            {
                return NotFound();
            }

            return View(userFromDb);
        }

        //post Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit (string id, ApplicationUser applicationUser)
        {
            if (id != applicationUser.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                ApplicationUser userFromDb = _db.ApplicationUser.Where(u => u.Id == id).FirstOrDefault();
                userFromDb.Name = applicationUser.Name;
                userFromDb.PhoneNumber = applicationUser.PhoneNumber;
                //what about changing email?
                _db.SaveChanges();
                return RedirectToAction(nameof(Index));

            }

            return View(applicationUser);
        }

        //GET Delete Action Method -- -- go to confirm page
        public IActionResult Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }
            ApplicationUser userFromDb = _db.ApplicationUser.Where(u => u.Id == id).FirstOrDefault();
            if (userFromDb == null)
            {
                return NotFound();
            }

            return View(userFromDb);
        }

        //POST Delete Action Method -- get entered data from GET and save to SQL
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(string id)
        {

            ApplicationUser userFromDb = _db.ApplicationUser.Where(u => u.Id == id).FirstOrDefault();
            userFromDb.LockoutEnd = DateTime.Now.AddYears(+100);
            _db.SaveChanges();
            return RedirectToAction(nameof(Index));  // or RedirectToAction("Index")

        }

    } // end class AdminUsersController : Controller
}  // end namespace GraniteHouse.Areas.Admin.Controllers

GraniteHouse/Areas/Admin/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using GraniteHouse.Data;
using GraniteHouse.Models;
using GraniteHouse.Models.ViewModel;
using GraniteHouse.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting.Internal;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace GraniteHouse.Areas.Admin.Controllers
{
    
    [Authorize(Roles = SD.SuperAdminEndUser)]
    [Area("Admin")]
    public class ProductsController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly HostingEnvironment _hostingEnvironment;

        [BindProperty]
        public ProductsViewModel ProductsVM { get; set; }

        public ProductsController(ApplicationDbContext db, HostingEnvironment hostingEnvironment)
        {
            _db = db;
            _hostingEnvironment = hostingEnvironment;
            ProductsVM = new ProductsViewModel()
            {
                ProductTypes = _db.ProductTypes.ToList(),
                SpecialTags = _db.SpecialTags.ToList(),
                Products = new Models.Products()
            };

        }
        public async Task<IActionResult> Index()
        {
            var products = _db.Products.Include(m => m.ProductTypes).Include(m => m.SpecialTags).OrderBy(m => m.Name);
            return View(await products.ToListAsync());
        }

        //Get : Products Create
        public IActionResult Create()
        {
            ProductsVM.Products.SpecialTagsID = 6;
            return View(ProductsVM); // productsVM needed to display pulldowns for product types and special tags.
        }

        //Post : Products Create
        [HttpPost, ActionName("Create")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreatePOST()
        {
            if (!ModelState.IsValid)
            {
                return View(ProductsVM);
            }

            _db.Products.Add(ProductsVM.Products);
            await _db.SaveChangesAsync();

            //Image being saved
            string webRootPath = _hostingEnvironment.WebRootPath;
            var files = HttpContext.Request.Form.Files;

            var productsFromDb = _db.Products.Find(ProductsVM.Products.Id);

            if (files.Count != 0)
            {
                //Image has been uploaded, product needs to be saved so we have the product.ID
                var uploads = Path.Combine(webRootPath, SD.ImageFolder);
                var extension = Path.GetExtension(files[0].FileName);

                using (var filestream = new FileStream(Path.Combine(uploads, ProductsVM.Products.Id + extension), FileMode.Create))
                {
                    files[0].CopyTo(filestream);
                }
                productsFromDb.image = @"\" + SD.ImageFolder + @"\" + ProductsVM.Products.Id + extension;
            }
            else
            {
                //when user does not upload image.  Copy the default_img.png to Product.Id + ".png"
                var uploads = Path.Combine(webRootPath, SD.ImageFolder + @"\" + SD.DefaultProductImage);
                System.IO.File.Copy(uploads, webRootPath + @"\" + SD.ImageFolder + @"\" + ProductsVM.Products.Id + ".png");
                productsFromDb.image = @"\" + SD.ImageFolder + @"\" + ProductsVM.Products.Id + ".png";
            }
            await _db.SaveChangesAsync();

            return RedirectToAction(nameof(Index));

        }

        //GET : Edit
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();  // NotFound() base controller method that returns a 404 html error.
            }

            ProductsVM.Products = await _db.Products.Include(m => m.SpecialTags).Include(m => m.ProductTypes).SingleOrDefaultAsync(m => m.Id == id);

            if (ProductsVM.Products == null)
            {
                return NotFound();
            }

            return View(ProductsVM);
        }


        //Post : Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id)
        {
            if (ModelState.IsValid)
            {
                string webRootPath = _hostingEnvironment.WebRootPath;
                var files = HttpContext.Request.Form.Files;
                // get existing product 
                var productFromDb = _db.Products.Where(m => m.Id == ProductsVM.Products.Id).FirstOrDefault();

                if (files.Count > 0 && files[0] != null)
                {
                    //if user uploads a new image, need to delete the old image file (since the product name has the ID as the filename).
                    // hmmm, no way to just delete an image and leave blank.
                    var uploads = Path.Combine(webRootPath, SD.ImageFolder);
                    var extension_new = Path.GetExtension(files[0].FileName);
                    var extension_old = Path.GetExtension(productFromDb.image);
              
                    if (System.IO.File.Exists(Path.Combine(uploads, ProductsVM.Products.Id + extension_old)))
                    {
                        System.IO.File.Delete(Path.Combine(uploads, ProductsVM.Products.Id + extension_old));
                    }
                    using (var filestream = new FileStream(Path.Combine(uploads, ProductsVM.Products.Id + extension_new), FileMode.Create))
                    {
                        files[0].CopyTo(filestream);
                    }
                    ProductsVM.Products.image = @"\" + SD.ImageFolder + @"\" + ProductsVM.Products.Id + extension_new;
                }

                if (ProductsVM.Products.image != null)
                {
                    productFromDb.image = ProductsVM.Products.image;
                }

                productFromDb.Name = ProductsVM.Products.Name;
                productFromDb.Description = ProductsVM.Products.Description;
                productFromDb.Price = ProductsVM.Products.Price;
                productFromDb.Available = ProductsVM.Products.Available;
                productFromDb.ProductTypeId = ProductsVM.Products.ProductTypeId;
                productFromDb.SpecialTagsID = ProductsVM.Products.SpecialTagsID;
                productFromDb.ShadeColor = ProductsVM.Products.ShadeColor;
                await _db.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }

            return View(ProductsVM);
        }

        //GET : Details
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            ProductsVM.Products = await _db.Products.Include(m => m.SpecialTags).Include(m => m.ProductTypes).SingleOrDefaultAsync(m => m.Id == id);

            if (ProductsVM.Products == null)
            {
                return NotFound();
            }

            return View(ProductsVM);
        }

        //GET : Delete
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            ProductsVM.Products = await _db.Products.Include(m => m.SpecialTags).Include(m => m.ProductTypes).SingleOrDefaultAsync(m => m.Id == id);

            if (ProductsVM.Products == null)
            {
                return NotFound();
            }

            return View(ProductsVM);
        }

        //POST : Delete
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            string webRootPath = _hostingEnvironment.WebRootPath;
            Products products = await _db.Products.FindAsync(id);

            if (products == null)
            {
                return NotFound();
            }
            else
            {
                var uploads = Path.Combine(webRootPath, SD.ImageFolder);
                var extension = Path.GetExtension(products.image);

                if (System.IO.File.Exists(Path.Combine(uploads, products.Id + extension)))
                {
                    System.IO.File.Delete(Path.Combine(uploads, products.Id + extension));
                }
                _db.Products.Remove(products);
                await _db.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
        }





    }
}

GraniteHouse/Areas/Admin/Controllers/SpecialTagsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GraniteHouse.Data;
using GraniteHouse.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace GraniteHouse.Models
{
    [Authorize(Roles = SD.AdminEndUser + "," + SD.SuperAdminEndUser)]
    [Area("Admin")]
    public class SpecialTagsController : Controller
    {
        private readonly ApplicationDbContext _db;


        /// <summary>
        /// Constructor to setup dependency injection for ProductTypes
        /// </summary>
        /// <param name="db"></param>
        public SpecialTagsController(ApplicationDbContext db)
        {
            _db = db;
        }

        // ******************* Methods  *******************************

        // GET: SpecialTags
        public ActionResult Index()
        {
            return View(_db.SpecialTags.ToList());
        }

        //GET Details Action Method -- show new specialTag entry screen
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var specialTag = await _db.SpecialTags.FindAsync(id);
            if (specialTag == null)
            {
                return NotFound();
            }

            return View(specialTag);
        }

        // GET: SpecialTags/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: SpecialTags/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(SpecialTags specialTags)
        {
            if (ModelState.IsValid)
            {
                _db.Add(specialTags);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View(specialTags);
            }

        }

        // GET: SpecialTags/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var specialTag = await _db.SpecialTags.FindAsync(id);
            if (specialTag == null)
            {
                return NotFound();
            }

            return View(specialTag);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, SpecialTags specialTags)
        {
            if (id != specialTags.Id)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                // updates all fields! need more specific update later on when there are more data columns.
                _db.Update(specialTags);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));  // or RedirectToAction("Index")
            }
            else
            {
                return View(specialTags);
            }

        }

        //GET Delete Action Method -- go to confirm page
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var specialTags = await _db.SpecialTags.FindAsync(id);
            if (specialTags == null)
            {
                return NotFound();
            }

            return View(specialTags);
        }

        //POST Delete Action Method -- get entered data from GET and save to SQL
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {

            var specialTag = await _db.SpecialTags.FindAsync(id);
            _db.SpecialTags.Remove(specialTag);
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));  // or RedirectToAction("Index")

        }
    }
}

GraniteHouse/Views/Shared/_AppointmentCustomerDetails.cshtml
@model GraniteHouse.Models.Appointments

<h4 class="text-success">Appointment Details</h4>

<div style="height:100px; background-color:aliceblue;" class="container border">
    <div class="col-12">
        <div class="row" style="padding-top:10px;">
            <div class="col-2">
                Full Name:
            </div>
            <div class="col-3">
                <input asp-for="@Model.CustomerName" readonly class="form-control" />
            </div>
            
            <div class="col-2"></div>
            
            <div class="col-2">
               Email:
            </div>
            <div class="col-3">
                <input asp-for="@Model.CustomerEmail" readonly class="form-control" />
            </div>
        </div>
     @*   why is instructor adding another column dive here, a ropw should be good enough???*@
        <div class="row" style="padding-top:10px;">
            <div class="col-2">
                Phone #:
            </div>
            <div class="col-3">
                <input asp-for="@Model.CustomerPhoneNumber" readonly class="form-control" />
            </div>

            <div class="col-2"></div>

            <div class="col-2">
               Appointment Time:
            </div>
            <div class="col-3">
                <input asp-for="@Model.AppointmentDate" readonly class="form-control" />
            </div>
        </div>

    </div>

</div>

GraniteHouse/Views/Shared/_AppointmentProductDetails.cshtml
@model List<GraniteHouse.Models.Products>
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

@if (Model.Count > 0)
{
    <table class="table table-striped" style="width:100%">
        <tr class="table-info">
            <th style="text-align:center; width:20%;"></th>

            <th style="text-align:center; ">
                <label asp-for="@Model.FirstOrDefault().Name"></label>
            </th>
            <th style="text-align:center; ">
                <label asp-for="@Model.FirstOrDefault().Description"></label>
            </th>
            <th style="text-align:center; ">
                @*<label asp-for="@Model.Products.FirstOrDefault().Price"></label>*@
                <label asp-for="@Model.FirstOrDefault().Price"></label>

            </th>
            <th style="text-align:center; ">
                <label asp-for="@Model.FirstOrDefault().ShadeColor"></label>
            </th>
            <th style="text-align:center; ">
                <label asp-for="@Model.FirstOrDefault().ProductTypes.Name"></label>
            </th>

            <th style="text-align:center; "></th>
        </tr>
        @foreach (var item in Model)
        {
            <tr padding:50px>
                <td>
                    <a asp-area="Customer" asp-controller="Home" asp-action="Details" asp-route-id="@item.Id">
                        <img src="@item.image" style="width:100%; margin:auto; display:block;
                                                               border-radius:5px; border:1px solid  #bbb9b9; " />
                    </a>
                </td>
                <td style="text-align:center;">
                    @Html.DisplayFor(i => item.Name)
                </td>
                <td style="text-align:center; ">
                    @Html.DisplayFor(i => item.Description)
                </td>
                <td style="text-align:center; ">
                    $@Html.DisplayFor(i => item.Price)
                </td>
                <td style="text-align:center; ">
                    @Html.DisplayFor(i => item.ShadeColor)
                </td>
                <td style="text-align:center; ">
                    @Html.DisplayFor(i => item.ProductTypes.Name)
                </td>
                <td style="text-align:center; ">
                    @*<button type="submit" class="btn btn-danger" asp-action="Remove" asp-route-id="@item.Id">
                        <i class="fas fa-trash-alt"></i>
                    </button>*@
                </td>
            </tr>
        }

    </table>

}

else
{
    <div>No Items Added To shopping cart ...</div>
}

GraniteHouse/Views/Shared/_AppointmentProductDetails_NoLink.cshtml
@model List<GraniteHouse.Models.Products>
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

@if (Model.Count > 0)
{
    <table class="table table-striped" style="width:100%">
        <tr class="table-info">
            <th style="text-align:center; width:20%;"></th>

            <th style="text-align:center; ">
                <label asp-for="@Model.FirstOrDefault().Name"></label>
            </th>
            <th style="text-align:center; ">
                <label asp-for="@Model.FirstOrDefault().Description"></label>
            </th>
            <th style="text-align:center; ">
                @*<label asp-for="@Model.Products.FirstOrDefault().Price"></label>*@
                <label asp-for="@Model.FirstOrDefault().Price"></label>

            </th>
            <th style="text-align:center; ">
                <label asp-for="@Model.FirstOrDefault().ShadeColor"></label>
            </th>
            <th style="text-align:center; ">
                <label asp-for="@Model.FirstOrDefault().ProductTypes.Name"></label>
            </th>

            <th style="text-align:center; "></th>
        </tr>
        @foreach (var item in Model)
        {
            <tr padding:50px>
                <td>
                    @*can't have img pointing back to product details page
                    <a asp-area="Customer" asp-controller="Home" asp-action="Details" asp-route-id="@item.Id">
                    <img src="@item.image" style="width:100%; margin:auto; display:block;
                                                  border-radius:5px; border:1px solid  #bbb9b9; " />
                    </a>*@
                    <img src="@item.image" style="width:100%; margin:auto; display:block;
                                                  border-radius:5px; border:1px solid  #bbb9b9; " />
                </td>
                <td style="text-align:center;">
                    @Html.DisplayFor(i => item.Name)
                </td>
                <td style="text-align:center; ">
                    @Html.DisplayFor(i => item.Description)
                </td>
                <td style="text-align:center; ">
                    $@Html.DisplayFor(i => item.Price)
                </td>
                <td style="text-align:center; ">
                    @Html.DisplayFor(i => item.ShadeColor)
                </td>
                <td style="text-align:center; ">
                    @Html.DisplayFor(i => item.ProductTypes.Name)
                </td>
                <td style="text-align:center; ">
                    @*<button type="submit" class="btn btn-danger" asp-action="Remove" asp-route-id="@item.Id">
                        <i class="fas fa-trash-alt"></i>
                    </button>*@
                </td>
            </tr>
        }

    </table>

}

else
{
    <div>No Items Added To shopping cart ...</div>
}

GraniteHouse/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@using GraniteHouse.Extensions
@using GraniteHouse.Utility

@inject IHttpContextAccessor HttpContextAccessor

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GraniteHouse</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/css/jquery-ui.css" />
        <link rel="stylesheet" href="~/css/jquery.timepicker.css" />

        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">

    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/css/jquery-ui.css" />
        <link rel="stylesheet" href="~/css/jquery.timepicker.css" />

        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">

    </environment>
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        <a class="navbar-brand" asp-area="Customer" asp-controller="Home" asp-action="Index">Granite House Home</a>
        <div class="collapse navbar-collapse">
            <ul class="navbar-nav mr-auto">
                @if (User.IsInRole(SD.SuperAdminEndUser))
                {
                    <li class="nav-item"><a class="nav-link" asp-area="Admin" asp-controller="Products" asp-action="Index">Products</a></li>
                }
                @if (User.IsInRole(SD.SuperAdminEndUser) || User.IsInRole(SD.AdminEndUser))
                {
                    <li class="nav-item"><a class="nav-link" asp-area="Admin" asp-controller="ProductTypes" asp-action="Index">Product Types</a></li>
                    <li class="nav-item"><a class="nav-link" asp-area="Admin" asp-controller="SpecialTags" asp-action="Index">Special Tags</a></li>
                    <li class="nav-item"><a class="nav-link" asp-area="Admin" asp-controller="Appointments" asp-action="Index">Appointments</a></li>
                }
                @if (User.IsInRole(SD.SuperAdminEndUser))
                {
                    <li class="nav-item"><a class="nav-link" asp-area="Admin" asp-controller="AdminUsers" asp-action="Index">Admin Users</a></li>
                }

                @if (HttpContextAccessor.HttpContext.Session.Get<List<int>>("ssShoppingCart") != null)
                {
                    <li style="color:white;">
                        <a asp-area="Customer" asp-controller="ShoppingCart" asp-action="Index" class="nav-link">
                            <i class="fas fa-shopping-cart"></i>&nbsp;
                            @{
                                var count = HttpContextAccessor.HttpContext.Session.Get<List<int>>("ssShoppingCart").Count;
                            }
                            (@count)
                        </a>
                    </li>
                }
                else
                {
                    <li style="color:white;">
                        <a asp-area="Customer" asp-controller="ShoppingCart" asp-action="Index" class="nav-link">
                            <i class="fas fa-shopping-cart"></i>&nbsp;
                            (0)
                        </a>
                    </li>
                }
            </ul>
        </div>
        <div>
            <partial name="_LoginPartial" />
        </div>
    </nav>




    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - GraniteHouse</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/js/jquery-ui.js" asp-append-version="true"></script>
        <script src="~/js/jquery.timepicker.js" asp-append-version="true"></script>

    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
        <script src="~/js/jquery-ui.js" asp-append-version="true"></script>
        <script src="~/js/jquery.timepicker.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

GraniteHouse/Views/Shared/_TableButtonPartial.cshtml
@model int
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<td style="width:150px">
    <div class="btn-group" role="group">
        <a type="button" class="btn btn-primary" href="@Url.Action("Edit/"+Model)">
            <i class="fas fa-edit"></i>
        </a>
        <a type="button" class="btn btn-success" href="@Url.Action("Details/"+Model)">
            <i class="far fa-list-alt"></i>
        </a>
        <a type="button" class="btn btn-danger" href="@Url.Action("Delete/"+Model)">
            <i class="fas fa-trash-alt"></i>
        </a>
    </div>

</td>